'use server';

/**
 * @fileOverview AI flow for generating product attributes, price range, and captions from a product photo and description.
 *
 * - photoToCatalog - A function that handles the image analysis and content generation process.
 * - PhotoToCatalogInput - The input type for the photoToCatalog function.
 * - PhotoToCatalogOutput - The return type for the photoToCata_log function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PhotoToCatalogInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      'A photo of the product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: \'data:<mimetype>;base64,<encoded_data>\'.'
    ),
  description: z.string().optional().describe('An optional description of the product.'),
});
export type PhotoToCatalogInput = z.infer<typeof PhotoToCatalogInputSchema>;

const PhotoToCatalogOutputSchema = z.object({
  attributes: z.array(z.string()).describe('Suggested attributes for the product.'),
  priceRange: z.string().describe('Suggested price range for the product in Indian Rupees (INR).'),
  captions: z.array(z.string()).describe('Autogenerated captions for the product.'),
  hindiCaptions: z.array(z.string()).describe('Autogenerated captions for the product in Hindi.'),
});
export type PhotoToCatalogOutput = z.infer<typeof PhotoToCatalogOutputSchema>;

export async function photoToCatalog(input: PhotoToCatalogInput): Promise<PhotoToCatalogOutput> {
  return photoToCatalogFlow(input);
}

const photoToCatalogFlow = ai.defineFlow(
  {
    name: 'photoToCatalogFlow',
    inputSchema: PhotoToCatalogInputSchema,
    outputSchema: PhotoToCatalogOutputSchema,
  },
  async input => {
    const {output} = await ai.generate({
        model: 'googleai/gemini-1.5-flash-latest',
        prompt: `You are an AI assistant that helps artisans create product listings.
    
      Analyze the provided product photo and the description (if available) to suggest relevant attributes, a reasonable price range in Indian Rupees (INR), and engaging captions in both English and Hindi.
      The artisan will use these suggestions to quickly list their items for sale.
    
      Analyze this image: ${input.photoDataUri}.
      ${input.description ? `Use this description as well: ${input.description}` : ''}
    `,
        output: {
            schema: PhotoToCatalogOutputSchema,
        }
    });
    return output!;
  }
);
